server:
  port: 8760

spring:
  application:
    name: microservice-wendao-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
        routes:
        - id: microservice-wendao-feed
          uri: lb://microservice-wendao-feed
          predicates:
            - Path=/feed/**
          filters:
            - StripPrefix=1
#      routes:
#        - id: after_route
#          uri: http://localhost:8763/hi
#          filters:
#            - AddRequestHeader=X-Request-Foo, Bar
#          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]

eureka:
  client:
    serviceUrl:
      defaultZone: http://host1:8761/eureka/

