server:
  port: 2000

spring:
  application:
    name: microservice-wendao-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true
        routes:
        - id: service-api-feed
          uri: lb://service-api-feed
          predicates:
            - Path=/feed/**
          filters:
            - StripPrefix=1
        - id: service-base-user
          uri: lb://service-base-user
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix = 2
            - Custom
        - id: service-content-qa
          uri: lb:service-content-qa
          predicates:
            - Path=/api/v1/question/**,/api/v1/answer/**
          filters:
            - StripPrefix = 2
#            - Custom

