server:
  port : 8761
eureka:
  instance:
    hostname: host1
    prefer-ip-address: true
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://host2:8762/eureka/
spring:
  application:
    name: microservice-wendao-eureka
  profiles: host1

---
server:
  port : 8762
eureka:
  instance:
    hostname: host2
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://host1:8761/eureka/
spring:
  application:
    name: microservice-wendao-eureka
  profiles: host2
