#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://host1:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: microservice-wendao-feign

feign:
  hystrix:
    enabled: true
